on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  1:
    runs-on: ubuntu-latest

    steps:
      - name: 2
        uses: actions/checkout@v3

      - name: 3
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 4
        run: |
          current_date=$(date +%s)
          echo "$current_date"

          awk -F ' ' -v current_date="$current_date" '
            {
              split($2, f, ".")
              line_date = mktime(f[3] " " f[2] " " f[1] " 00 00 00")
              if (line_date >= current_date) print $0
            }
          ' codes.txt > temp.txt && mv temp.txt codes.txt

      - name: 5
        run: |
          echo "$(date +%s)" | cat - codes.txt > temp.txt && mv temp.txt codes.txt

      - name: 6
        run: |
          git add codes.txt
          git commit -m "Update" || echo "No changes"

      - name: 7
        run: git fetch --all

      - name: 8
        run: git push origin HEAD || git push origin HEAD --force
