on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  faw:
    runs-on: ubuntu-latest

    steps:
      - name: ywa
        uses: actions/checkout@v3

      - name: gfaw
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: ysd
        run: |
          current_date=$(date +%s)
          echo "Current Unix timestamp: $current_date"

          awk -F ' ' -v current_date="$current_date" '
            {
              line_date=$2
              
              if (line_date >= current_date) print $0
            }
          ' codes.txt > temp.txt && mv temp.txt codes.txt

      - name: taw
        run: |
          echo "$(date +%s)" | cat - codes.txt > temp.txt && mv temp.txt codes.txt

      - name: ghdf
        run: |
          git add codes.txt
          git commit -m "Update" || echo "No changes"

      - name: fg
        run: git fetch --all

      - name: 8
        run: git push origin HEAD || git push origin HEAD --force
